# Generated by Django 2.2.7 on 2020-06-19 19:55

from django.db import migrations, models
import kpi.fields.kpi_uid
import private_storage.fields
import private_storage.storage.files


class Migration(migrations.Migration):

    dependencies = [
        ('help', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inappmessage',
            name='published',
            field=models.BooleanField(default=False, help_text='When published, this message appears to all users. It otherwise appears only to the last editor'),
        ),
        migrations.AlterField(
            model_name='inappmessage',
            name='uid',
            field=kpi.fields.kpi_uid.KpiUidField(uid_prefix='iam'),
        ),
        migrations.AlterField(
            model_name='inappmessagefile',
            name='content',
            field=private_storage.fields.PrivateFileField(storage=private_storage.storage.files.PrivateFileSystemStorage(), upload_to='__in_app_message/%Y/%m/%d/'),
        ),
    ]
