# Generated by Django 2.2.7 on 2020-06-20 18:27

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('kpi', '0025_auto_20200619_1955'),
    ]

    operations = [
        migrations.CreateModel(
            name='LocationAccess',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kebeles', models.ManyToManyField(to='kpi.Kebele')),
                ('regions', models.ManyToManyField(to='kpi.Region')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='location_access', to=settings.AUTH_USER_MODEL)),
                ('woredas', models.ManyToManyField(to='kpi.Woreda')),
                ('zones', models.ManyToManyField(to='kpi.Zone')),
            ],
        ),
    ]
