# Generated by Django 2.2.7 on 2020-06-20 19:00

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kpi', '0026_locationaccess'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='locationaccess',
            name='id',
        ),
        migrations.AlterField(
            model_name='locationaccess',
            name='kebeles',
            field=models.ManyToManyField(blank=True, to='kpi.Kebele'),
        ),
        migrations.AlterField(
            model_name='locationaccess',
            name='regions',
            field=models.ManyToManyField(blank=True, to='kpi.Region'),
        ),
        migrations.AlterField(
            model_name='locationaccess',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='location_access', serialize=False, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='locationaccess',
            name='woredas',
            field=models.ManyToManyField(blank=True, to='kpi.Woreda'),
        ),
        migrations.AlterField(
            model_name='locationaccess',
            name='zones',
            field=models.ManyToManyField(blank=True, to='kpi.Zone'),
        ),
    ]
